title: Title of your CV site
profile_img: /assets/img/Cani Foto.jpeg
icon_img: /assets/img/icon.webp

name: "Ragdad Cani Miranti"
job: "〈Central Bureau of Statistics, Indonesia〉"

phone_number: 012-345-6789
address: Manchester, United Kingdom
email: ragdad.miranti@postgrad.manchester.ac.uk
linkedin_username: https://www.linkedin.com/in/ragdad-cani-miranti-a9a97668/
github_username: canimiranti
instagram_username: canimiranti
researchgate_username:Ragdad-Miranti
facebook_username:ragdad.miranti
youtube_username: "https://www.youtube.com/channel/UC2VvClDr_V7y0OOEmppNy3Q"
blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl: /cancan91

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
